### ISSUE TITLE
Add cli flag to only include results if they have query strings

### ISSUE THREAD

**Issue by ameenmaali** [ameenmaali/urldedupe#11]
Add (`-qs | --query-strings-only`) flag to only include urls in outputs if they have query strings

**Comment by larskraemer** [comment]
I would suggest making these kind of filter operations a bit more uniform by adding a flag like `--filter`. This would let us implement something like `--filter qs`, to only allow URLs with query strings, but potentially also `--filter scheme=http` to only output URLs which specify a http scheme. Adding separate flags for all potentially useful options probably isn't a good idea usability-wise.

**Comment by ameenmaali** [comment]
Nice idea, decided to add `-m|--mode` flags. Keeping in the other flags as well in case people prefer that option. If the amount of modes gets out of hand, we could of course remove those. Did some refactoring of the flag parsing as well (https://github.com/ameenmaali/urldedupe/commit/72f2c61def5f9a083fe9da8440a430db3a596408)
